AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://cloud-service-namer/c3c47d3979db01df13b2003ae539a823
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /names
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
